export { configuration as whatWomenWantConfig } from './whatwomenwant'
export { configuration as whatYoungPeopleWantConfig } from './whatyoungpeoplewant'
export { configuration as midwivesVoicesConfig } from './midwivesvoices'
export { configuration as healthWellBeingConfig } from './healthwellbeing'
export { configuration as gizConfig } from './giz'
export { configuration as wwwPakistanConfig } from './wwwpakistan'
